# Generated by Django 2.1 on 2018-08-04 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embedded',
            field=models.CharField(max_length=255, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255, validators=[django.core.validators.URLValidator()]),
        ),
    ]
