# Generated by Django 2.1 on 2018-08-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180804_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='isActive',
        ),
    ]
